### ISSUE TITLE
Unable to restore architecture id mappings

### ISSUE THREAD

**Issue by jrozner** [jrozner/binja-msp430#14]
Unclear what this means but anytime firmware is opened these error messages are printed.
<img width="525" alt="Screenshot 2024-05-31 at 1 36 14 PM" src="https://github.com/jrozner/binja-msp430/assets/26415/cd9ee218-f28e-4694-b6f3-ddc37a050c8a">

**Comment by plafosse** [comment]
This will be fixed in 4.1.5850

**Comment by jrozner** [comment]
Confirmed this is fixed
